language: go
go:
  - 1.9.x

sudo: false

before_install:
  - go get github.com/vbatts/git-validation

install: true

script:
  - git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
  - make test
